project_name: cc
release:
  github:
    owner: zbindenren
    name: cc
builds:
    - id: changelog
      goos:
        - freebsd
        - darwin
        - linux
        - windows
      goarch:
        - amd64
      main: cmd/main.go
      binary: changelog
      env:
        - CGO_ENABLED=0
dockers:
    - ids:
        - changelog
      goos: linux
      goarch: amd64
      dockerfile: packaging/docker/Dockerfile
      image_templates:
        - 'zbindenren/{{ .ProjectName }}:{{ .Major }}.{{ .Minor }}.{{ .Patch }}'
        - 'zbindenren/{{ .ProjectName }}:{{ .Major }}.{{ .Minor }}'
        - 'zbindenren/{{ .ProjectName }}:{{ .Major }}'
        - 'zbindenren/{{ .ProjectName }}:latest'
      build_flag_templates:
        - --label=org.opencontainers.image.version={{ .Version }}
        - --label=org.opencontainers.image.url=https://github.com/zbindenren/cc
        - --label=org.opencontainers.image.source=https://github.com/zbindenren/cc
        - --label=org.opencontainers.image.revision={{ .ShortCommit }}
        - --label=org.opencontainers.image.created={{ .Date }}
checksum:
    name_template: checksums.txt
before:
    hooks:
        - go generate ./...
