project_name: cc
release:
  github:
    owner: zbindenren
    name: cc
builds:
    - id: changelog
      goos:
        - freebsd
        - darwin
        - linux
        - windows
      goarch:
        - amd64
      main: cmd/main.go
      binary: changelog
      env:
        - CGO_ENABLED=0
checksum:
    name_template: checksums.txt
before:
    hooks:
        - go generate ./...
